### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by gamezinfantes** [gakimball/react-inky#1]
`var inky = require('react-inky');`

`Error: Cannot find module 'react-inky'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Documentos\GitHub\react-ink\index.js:1:74)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)`

**Comment by gakimball** [comment]
Sorry I missed this, friend! I blame not getting GitHub emails. I'll be addressing it this week.

**Comment by gakimball** [comment]
Fixed in version 0.2.0.

**Comment by jp7carlos** [comment]
Hi, I don't know what happened, but it seems to still point at /lib/index.js:

* https://github.com/gakimball/react-inky/blob/master/package.json#L5

**Comment by gakimball** [comment]
`src/` is compiled to `lib/` before the package is published, so pointing to `lib/index.js` is correct. Are you having trouble importing the package in your code?

**Comment by jp7carlos** [comment]
Thx for replying. 

After npm install, the files in ./node_modules/react-inky looks like this (no lib folder):

* LICENSE
* README.md
* book.json 
* docs
* package.json 
* src

**Comment by gakimball** [comment]
@jp7carlos Resolved with `0.2.1`, thanks for your patience! 👍
