### ISSUE TITLE
How to style the component ?

### ISSUE THREAD

**Issue by max8hine** [gakimball/react-inky#12]
### 3 questions about this library, but more related to implementation question.

*1. How to put <style /> tag with css into the **header section*** 
*and does this library needs to add foundation-email to work?*

I run node-sass to compile scss to css but not able to find the place to add the compiled css

```js 
// seems no props have been provided to add css string into style tag
function inky(elem = '') {
	return `
	<style>
        <!-- Your CSS to inline should be added here -->
    </style>
	<body>${elem}</body>	`
}
```

*2. seems there is an error in docs*
At the button of [setup.md](https://github.com/gakimball/react-inky/blob/master/docs/setup.md), 
``` js
renderToString(inky(template)) // the docs
inky(renderToString(template)) // the source code
```

*3. how to run it in **create-react-app***
```jsx
/** [create-react-app]

I'm using it on styling email to take advantage of its hot-reloading feature.

Looking for the better way to implement this lib with create-react-app
The code below will overlap with default html elements witch generated by browser.
It means You will have two <header/> inside of <html>
*/
// ./src/index.js
import React from 'react'
import { renderToString } from 'react-dom/server';
import inky from 'react-inky';
import registerServiceWorker from './registerServiceWorker';

import ReactEmail from './emails/pages/ReactEmail';

const email = <ReactEmail />;
document.body.outerHTML = inky(renderToString(email))
```

> Thank you for making this incredible library that works so well with **express-react-views** in the server-side-rendering.
> Currently, I use it in express with **mailgun** together. I could provide an example with about how to do it in SSR with **express-react-view** + **nodemailer** or **mailgun** 
> I love what you did in Zurb but didn't know this library exist until now.
> I've been searching by keywords `react email template`, but couldn't find this 
> library in Google, maybe adding some more keywords on github would help.

**Comment by gakimball** [comment]
Hey there! I was writing a response to your comment yesterday, but I see you edited it.

> 2. seems there is an error in docs

The second example is right—I'll get that fixed. `renderToString()` creates the HTML of the email, and then `inky()` wraps that HTML in the required boilerplate.

> I run node-sass to compile scss to css but not able to find the place to add the compiled css

I'm looking into making some changes to this library soon, and this is something I'd like to address. Certain parts of the wrapper HTML are essential, but it should be easier to edit all the stuff in `<head>`.

Your initial issue was asking about how inlining would work, and if you're interested in seeing an example of what the general steps are, I wrote a library that does it called [scow](https://www.npmjs.com/package/scow). The readme for that library includes a list of steps. However, it only works on `.html` files that are already in the filesystem, so it might not work for your use case.

Something you could do in the mean time is look at the code used on the [foundation-emails-template](https://github.com/zurb/foundation-emails-template/blob/master/src/layouts/default.html). This is more or less the boilerplate react-inky uses. You could use this instead of the `inky()` function, and change the HTML how you'd like.

Thanks for using react-inky! :)

**Comment by gakimball** [comment]
Here's my idea for how an editable layout would work: #13

**Comment by max8hine** [comment]
I was editing my question actually twice yesterday,
My initial question was vague, sorry for I opened an issue without thinking well.

The idea for #13 looks simple and solid. 
look forward to the change.

[scow](https://www.npmjs.com/package/scow) looks awesome and useful.
I will try **scow** when I work on the **Mailchimp**.

**Comment by max8hine** [comment]
Oh, based on my understanding

#13 means,
All the HTML tags will be written in React Component, including `<html/>` but except the `doctype`?

If it is true, it will benefit the person who also uses **facebook/express-react-views** as Express's view engine in the node.js project.

which the library uses `renderToString` API to render HTML internally and add `<!DOCTYPE html>` on top during the rendering process by default.

In this way, the `renderToString(inky(template))` in **setup.md** will be the correct one in the future.

**Comment by gakimball** [comment]
Hey, I did it! You can run `npm install gakimball/react-inky#0.3` to try it out. The documentation for it is [here](https://github.com/gakimball/react-inky/blob/25a28f46d2eca7b6bde9e06240a3bcd9d77ec39d/docs/setup.md).

**Comment by max8hine** [comment]
Amazing! that's fast!!
gonna try it now =)👍

**Comment by gakimball** [comment]
I also just published a proper npm version under a `next` tag: `npm install react-inky@next`. I forgot that installing directly from GitHub won't quite work, because you don't get the compiled JavaScript.

It also requires React 16.2.

**Comment by max8hine** [comment]
🙌

The link below is my step-up about how to run this lib in **create-react-app** for developing. Just put here for someone might needs =)
[react-inky-example](https://github.com/max8hine/react-inky-example)

**Comment by gakimball** [comment]
What was the error?

One thing to note is that `<Inky />` creates a full HTML document, including the top-level `<html>` tag, so whatever template you drop the code into should just have a doctype and nothing else.

**Comment by max8hine** [comment]
Sorry to get back late.

I think the <Inky> don't take children props.

``` jsx
<Inky>
	<Inky.Head>
		<link rel="stylesheet" href="/styles/emails/index.css"/>
	</Inky.Head>
	<Inky.Body>
		<Email />  // OK
	</Inky.Body>
</Inky>
```

``` jsx
<Inky>
	<Inky.Head>
		<link rel="stylesheet" href="/styles/emails/index.css"/>
	</Inky.Head>
	<Inky.Body>
		{this.props.children} // Error
	</Inky.Body>
</Inky>
```

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at invariant (/Users/maxshine/Documents/workspace/express-react-email/node_modules/fbjs/lib/invariant.js:42:15)
    at ReactDOMServerRenderer.render (/Users/maxshine/Documents/workspace/express-react-email/node_modules/react-dom/cjs/react-dom-server.node.development.js:2477:7)
    at ReactDOMServerRenderer.read (/Users/maxshine/Documents/workspace/express-react-email/node_modules/react-dom/cjs/react-dom-server.node.development.js:2307:19)
    at Object.renderToStaticMarkup (/Users/maxshine/Documents/workspace/express-react-email/node_modules/react-dom/cjs/react-dom-server.node.development.js:2690:25)
    at View.renderFile [as engine] (/Users/maxshine/Documents/workspace/express-react-email/node_modules/express-react-views/index.js:68:32)
    at View.render (/Users/maxshine/Documents/workspace/express-react-email/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/maxshine/Documents/workspace/express-react-email/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/maxshine/Documents/workspace/express-react-email/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/maxshine/Documents/workspace/express-react-email/node_modules/express/lib/response.js:1008:7)
    at module.exports (/Users/maxshine/Documents/workspace/express-react-email/routes/actions/home.js:52:14)
```

**Comment by gakimball** [comment]
I would double-check whatever `this.props.children` is by logging it to the console. It sounds like whatever you're putting inside `<Inky.Body />` isn't a React component.

**Comment by gakimball** [comment]
Also, I'd recommend getting rid of this `<div>` [in your Express code](https://github.com/max8hine/express-react-email/blob/master/views/emails/greeting.jsx#L9), because it might mess up the layout on some email clients.

**Comment by max8hine** [comment]
The `<div>` I put there, was just to try render it individually to see did the code work or not.

It was wrapped by `<Layout>` component, which is `<Inky>` component, I was using Inky as a HOC.

I don't know `<div>` will mess up the layout in some email clients. I will keep that in mind, thank you for point it out =)

**Comment by gakimball** [comment]
Were you able to figure anything else out? I'm fairly certain that the issue is not with the `<Inky>` components not passing children—you can see in the code [here](https://github.com/gakimball/react-inky/blob/875c6ddb0a9071f6cacfc6f768100e822965ec95/src/Html.js) that's all they do.

I'd recommend using `console.log` on all three of the HTML components: `Inky`, `Inky.Head`, and `Inky.Body`. Make sure they're all functions, which means they're being imported correctly. It could be some weird import/export issue. If those are all working, then make sure whatever you're passing into the Inky components is also a function. The error message you posted said that an object was used as a React component instead of a function.

**Comment by gakimball** [comment]
Closing due to inactivity. If you ever want to revisit this, let me know! 👌
